DROP TABLE PLAYLIST_CANCIONES;
DROP TABLE PLAYLIST_USUARIOS;
DROP TABLE ALBUMES_CANCIONES;
DROP TABLE PLAYLIST;
DROP TABLE ALBUMES;
DROP TABLE CANCIONES;
DROP TABLE ARTISTAS;
DROP TABLE GENEROS;
DROP TABLE USUARIOS;
DROP TABLE TIPO_USUAIRO;
DROP TABLE PAIS;


CREATE TABLE TIPO_USUAIRO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROL VARCHAR(10) NOT NULL
);


CREATE TABLE GENEROS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_GENERO VARCHAR2(100) NOT NULL
);

CREATE TABLE PAIS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_PAIS VARCHAR2(100) NOT NULL
);

CREATE TABLE ARTISTAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_PAIS NUMBER,
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID)
);

CREATE TABLE ALBUMES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    ANIO_LANZAMIENTO NUMBER(4) NOT NULL,
    ID_ARTISTA NUMBER,
    FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTAS(ID)
);

CREATE TABLE CANCIONES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY  PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    LANZAMINETO NUMBER(4) NOT NULL,
    ID_ARTISTA NUMBER,
    FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTAS(ID),
    ID_GENERO NUMBER NOT NULL,
    FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID) 
);

CREATE TABLE ALBUMES_CANCIONES (
    ID_ALBUM NUMBER,
    FOREIGN KEY (ID_ALBUM) REFERENCES ALBUMES(ID),
    ID_CANCION NUMBER,
    FOREIGN KEY (ID_CANCION) REFERENCES CANCIONES(ID)
);

CREATE TABLE USUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID_TIPO_USUARIO NUMBER,
    FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TIPO_USUAIRO(ID)
);

CREATE TABLE PLAYLIST (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_PLAYLIST VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID_USUARIO NUMBER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE PLAYLIST_CANCIONES (
    ID_PLAYLIST NUMBER,
    FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST(ID),
    ID_CANCION NUMBER,
    FOREIGN KEY (ID_CANCION) REFERENCES CANCIONES(ID)
);

CREATE TABLE PLAYLIST_USUARIOS (
    ID_PLAYLIST NUMBER,
    FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST(ID),
    ID_USUARIO NUMBER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

INSERT INTO TIPO_USUAIRO (ROL) VALUES ('Premium');
INSERT INTO TIPO_USUAIRO (ROL) VALUES ('Familiar');
INSERT INTO TIPO_USUARIO (ROL) VALUES ('Estandar');
COMMIT;

INSERT INTO GENEROS (NOMBRE_GENERO) VALUES ('Rock');
INSERT INTO GENEROS (NOMBRE_GENERO) VALUES ('Pop');
INSERT INTO GENEREOS (NOMBRE_GENERO) VALUES ('Hip-hop');
COMMIT;

INSERT INTO PAIS (NOMBRE_PAIS) VALUES ('Canada');
INSERT INTO PAIS (NOMBRE_PAIS) VALUES ('Chile');
INSERT INTO PAIS (NOMBRE_PAIS) VALUES ('Estados Unidos');
COMMIT;

INSERT INTO ARTISTAS (NOMBRE, ID_PAIS) VALUES ('The Beatles', 2);
INSERT INTO ARTISTAS (NOMBRE, ID_PAIS) VALUES ('Michael Jackson', 2);
INSERT INTO ARTISTAS (NOMBRE, ID_PAIS) VALUES ('Madonna', 1);
COMMIT;

INSERT INTO ALBUMES (TITULO, ANIO_LANZAMIENTO, ID_ARTISTA) VALUES ('Abbey Road', 1969, 1);
INSERT INTO ALBUMES (TITULO, ANIO_LANZAMIENTO, ID_ARTISTA) VALUES ('Thriller', 1982, 2);
COMMIT;

INSERT INTO CANCIONES (TITULO, LANZAMINETO, ID_ARTISTA, ID_GENERO) VALUES ('Las tortugas', 2004, 2, 1);
INSERT INTO CANCIONES (TITULO, LANZAMINETO, ID_ARTISTA, ID_GENERO) VALUES ('200 copas', 2005, 3, 2);
COMMIT;

INSERT INTO ALBUMES_CANCIONES (ID_ALBUM, ID_CANCION) VALUES (1,2);
INSERT INTO ALBUMES_CANCIONES (ID_ALBUM, ID_CANCION) VALUES (2,1);
COMMIT;

INSERT INTO USUARIOS (NOMBRE_USUARIO, EMAIL, FECHA_REGISTRO, ID_TIPO_USUARIO) VALUES ('Dani', 'Dn@gmail.com', SYSTIMESTAMP, 1);
INSERT INTO USUARIOS (NOMBRE_USUARIO, EMAIL, FECHA_REGISTRO, ID_TIPO_USUARIO) VALUES ('Ana', 'an@gmail.com', SYSTIMESTAMP, 2);
COMMIT;

INSERT INTO PLAYLIST (NOMBRE_PLAYLIST, DESCRIPCION, FECHA_CREACION, ID_USUARIO) VALUES ('Rock Classics', 'Best of rock music', SYSTIMESTAMP, 1);
INSERT INTO PLAYLIST (NOMBRE_PLAYLIST, DESCRIPCION, FECHA_CREACION, ID_USUARIO) VALUES ('Pop Hits', 'Top pop songs', SYSTIMESTAMP, 2);
COMMIT;

INSERT INTO PLAYLIST_CANCIONES (ID_PLAYLIST, ID_CANCION) VALUES (1, 2);
INSERT INTO PLAYLIST_CANCIONES (ID_PLAYLIST, ID_CANCION) VALUES (2, 1);
COMMIT;

INSERT INTO PLAYLIST_USUARIOS (ID_PLAYLIST, ID_USUARIO) VALUES (1, 1);
INSERT INTO PLAYLIST_USUARIOS (ID_PLAYLIST, ID_USUARIO) VALUES (2, 2);

COMMIT;
